### PR TITLE
Update @solid/oidc-rp version to 0.10.0

### PR DESCRIPTION
**Pull request by mfornos**
@solid/oidc-rp was updated to 0.10.0, this version removes the dependencies with @trust/json-document and @trust/webcrypto. A good thing because the JSON schema validator causes some problems with Content Security Policies. :smile_cat:

### CODE REVIEW

**Comment by jaxoncreed** [comment]
LGTM, just need to pull down and manually test

**Comment by michielbdejong** [comment]
The dependency update is included in https://github.com/solid/solid-auth-client/pull/163.
@mfornos can you say a bit more about the changes you made in https://github.com/solid/solid-auth-client/pull/150/files#diff-2386e1ce48920481f393939fd08834d1?

**Comment by mfornos** [comment]
Sure! :smile_cat:

Changes done:
1. The path of the import for the "oidc-rp" dependency from "lib" to "src".
2. Fulfilled the default values for RelyingParty as expected in its constructor: https://github.com/solid/oidc-rp/blob/6d007019bd9fa54d1b2783f72018321b3891d1c6/src/RelyingParty.js#L63

**Comment by michielbdejong** [comment]
Done! Thanks.

**Pull request closed without merging**
